---
- block:
    - name: Collect the list of host authentications
      uri:
        url: "https://{{ inventory_hostname }}/api/hosts/?filter[]=name={{ hostvars[item].vmw_host_name }}&expand=resources&attributes=authentications"
        user: "{{ miq_app_username | default('admin') }}"
        password: "{{ miq_app_password | default('smartvm') }}"
        method: GET
        validate_certs: no
      register: host_json
      until: host_json.json.subcount == 1
      retries: 12
      delay: 5

    - set_fact:
        query: "resources[?name=='{{ hostvars[item].vmw_host_name }}'].id"

    - name: Extracting host id from JSON
      set_fact:
        host_id: "{{ host_json.json | json_query(query) | first }}"

    - name: Add authentication for the host
      uri:
        url: "https://{{ inventory_hostname }}/api/hosts/{{ host_id }}/"
        user: "{{ miq_app_username | default('admin') }}"
        password: "{{ miq_app_password | default('smartvm') }}"
        method: POST
        validate_certs: no
        body_format: json
        body:
          action: edit
          resource:
            credentials:
              auth_type: default
              userid: root
              password: "{{ hostvars[item].root_password }}"
  tags:
    - miq_config_vmware_esx_hosts
